
[General]
	chatNotifications = true

[Mobs]

	[Mobs.GhostOfCaptainCornelia]
		#Range: 0.0 ~ 10.0
		movementSpeed = 0.2
		#Range: 1.0 ~ 100000.0
		maxHealth = 200.0
		#Range: 0.0 ~ 1000.0
		armor = 16.0
		#Range: 1.0 ~ 1000.0
		attackDamage = 1.0
		#Range: 0.0 ~ 10.0
		knockbackResistance = 0.5
		#Range: 0.0 ~ 10.0
		attackKnockback = 2.0
		#Range: 1.0 ~ 256.0
		followRange = 128.0
		pullAndSpinTargets = true
		#Range: 0 ~ 1000
		regenerationSkillUses = 2

	[Mobs.Anglerfish]
		#Range: 0.0 ~ 100.0
		swimSpeed = 3.0
		#Range: 1.0 ~ 100000.0
		maxHealth = 40.0
		#Range: 0.0 ~ 1000.0
		armor = 2.0
		#Range: 0.0 ~ 10.0
		knockbackResistance = 0.0
		#Range: 1.0 ~ 1000.0
		attackDamage = 6.0
		#Range: 0.0 ~ 10.0
		attackKnockback = 1.0
		#Range: 1.0 ~ 256.0
		followRange = 48.0

	[Mobs.Maw]
		#Range: 0.0 ~ 10.0
		movementSpeed = 0.2
		#Range: 0.0 ~ 100.0
		swimSpeed = 5.0
		#Range: 1.0 ~ 100000.0
		maxHealth = 20.0
		#Range: 0.0 ~ 1000.0
		armor = 0.0
		#Range: 0.0 ~ 10.0
		knockbackResistance = 0.0
		#Range: 1.0 ~ 1000.0
		attackDamage = 4.0
		#Range: 0.0 ~ 10.0
		attackKnockback = 0.3
		#Range: 1.0 ~ 256.0
		followRange = 24.0

	[Mobs.TorturedSoul]
		#Range: 0.0 ~ 10.0
		movementSpeed = 0.2
		#Range: 0.0 ~ 100.0
		swimSpeed = 3.0
		#Range: 1.0 ~ 100000.0
		maxHealth = 30.0
		#Range: 0.0 ~ 1000.0
		armor = 4.0
		#Range: 0.0 ~ 10.0
		knockbackResistance = 0.0
		#Range: 1.0 ~ 1000.0
		attackDamage = 7.0
		#Range: 0.0 ~ 10.0
		attackKnockback = 0.7
		#Range: 1.0 ~ 256.0
		followRange = 24.0

	[Mobs.MotherOfTheMaze]
		#Range: 0.0 ~ 100.0
		swimSpeed = 3.0
		#Range: 1.0 ~ 100000.0
		maxHealth = 100.0
		#Range: 0.0 ~ 1000.0
		armor = 6.0
		#Range: 0.0 ~ 10.0
		knockbackResistance = 0.2
		#Range: 1.0 ~ 1000.0
		attackDamage = 5.0
		#Range: 0.0 ~ 10.0
		attackKnockback = 0.5
		#Range: 1.0 ~ 256.0
		followRange = 128.0

	[Mobs.Eel]
		#Range: 1.0 ~ 100000.0
		maxHealth = 180.0
		#Range: 0.0 ~ 1000.0
		armor = 20.0
		#Range: 1.0 ~ 1000.0
		attackDamage = 8.0
		#Range: 0.0 ~ 10.0
		attackKnockback = 2.0
		#Range: 1.0 ~ 256.0
		followRange = 32.0

