
[Rendering]

	[Rendering."Mob Model Improvements"]
		#Makes Moas resemble their Mutation models
		"Moa Model Improvements" = true
		#Determines whether the updated Moa model should use more peaceful-appearing toes, or more aggressive talons
		#Allowed Values: toes, talons
		"Moa Foot Type" = "toes"
		#Makes Cockatrices look far better
		"Cockatrice Model Improvements" = true
		#Makes some small edits to the zephyr model to make it more lore-accurate
		"Zephyr Model Improvements" = true
		#Improves the Sheepuff model, using a design taking elements both from older Aether II: Highlands Builds, and the lore-accurate design.
		"Sheepuff Model Improvements" = true
		#Improves the model for Sentries, giving them a new model and a springy jump animation
		"Sentry Model Improvements" = true

	[Rendering.Particles]
		#Improves the leaf particles for Golden Oaks, Gilded Oaks, and Crystal Trees, based on Minecraft 1.20's new cherry tree particles.
		"Better Leaf Particles" = true

[Audio]
	#Enables a slamming sound for mimics. Disable if it gets too annoying XD
	"Mimic Slam Sound Effect" = true

[Packs]
	#Automatically adds the overrides pack when disabled.
	"Auto-Apply Overrides Pack" = true

[Internal]
	#Internal value to decide if it is the first startup and the base Aether configs should be modified. DO NOT EDIT THIS VALUE, unless you want things to break!
	"First startup, change Aether configs (DO NOT CHANGE)" = false
	#Leftover value. May get used in a future update, or get removed.
	"Version ID" = "undefined"

