
# Let's Configure Delightful
[Knives]
	adamantium_knife = true
	alf_knife = true
	allthemodium_knife = true
	amethyst_knife = false
	black_opal_knife = true
	blazing_knife = true
	bone_knife = false
	brass_knife = true
	bronze_knife = true
	cloggrum_knife = true
	constantan_knife = true
	copper_knife = false
	crystalline_knife = true
	draco_arcanus_knife = true
	electrum_knife = true
	elementium_knife = true
	emerald_knife = false
	enderite_knife = true
	experience_knife = true
	fiery_knife = true
	forgotten_knife = true
	froststeel_knife = true
	gilded_netherite_knife = true
	gilded_quartz_knife = true
	gravitite_knife = true
	holystone_knife = true
	infused_veridium_knife = true
	invar_knife = true
	ironwood_knife = true
	kiwano_knife = true
	knightmetal_knife = true
	lapis_lazuli_knife = false
	large_amethyst_knife = true
	lead_knife = true
	leaf_knife = true
	living_knife = true
	manasteel_knife = true
	mythril_knife = true
	necronium_knife = true
	netherite_opal_knife = true
	nickel_knife = true
	obsidian_infused_enderite_knife = true
	onyx_knife = true
	osmium_knife = true
	pendorite_knife = true
	refined_glowstone_knife = true
	refined_obsidian_knife = true
	rose_gold_knife = true
	silver_knife = true
	sinisite_knife = true
	skyjade_knife = true
	skyroot_knife = true
	soul_steel_knife = true
	steel_knife = true
	steeleaf_knife = true
	stellium_knife = true
	stratus_knife = true
	terra_knife = true
	thyrium_knife = true
	tin_knife = true
	utherium_knife = true
	veridium_knife = true
	warden_knife = true
	zanite_knife = true
	zinc_knife = true

["Pie Overhauls"]
	blueberry_pie_slice = true
	crimson_berry_pie_slice = true
	gloomgourd_pie_slice = true
	green_apple_pie_slice = true
	nightshade_berry_pie_slice = true
	pumpkin_pie_slice = true
	salmonberry_pie_slice = true
	source_berry_pie_slice = true

["Registry & Recipes"]
	acorn = true
	acorn_sack = true
	animal_fat = true
	animal_oil_bottle = true
	azalea_tea = true
	baobab_fruit_crate = true
	basalt_cabinet = true
	berry_matcha_latte = true
	blueberry_sack = true
	cactus_flesh = true
	cactus_steak = true
	cantaloupe = true
	cantaloupe_slice = true
	cheeseburger = true
	chopped_clover = true
	chunk_nugget = true
	chunkwich = true
	coconut_curry = true
	cooked_goat = false
	cooked_marshmallow_stick = true
	cooked_venison_chops = true
	crab_rangoon = true
	crimson_berry_sack = true
	deluxe_cheeseburger = true
	ender_nectar = true
	field_salad = true
	glow_jelly_bottle = true
	green_apple_crate = true
	green_tea_leaf = true
	honey_glazed_walnut = true
	jelly_bottle = true
	joshua_fruit_crate = true
	lavender_tea = true
	marshmallow_stick = true
	matcha = true
	matcha_ice_cream = true
	matcha_ice_cream_block = true
	matcha_latte = true
	mini_melon = true
	nightshade_berry_sack = true
	nut_butter_and_jelly_sandwich = true
	nut_butter_bottle = true
	prickly_pear_juice = true
	quartz_cabinet = true
	raw_goat = false
	rock_candy = true
	salmonberries = true
	salmonberry_gummy = true
	salmonberry_ice_cream = true
	salmonberry_ice_cream_block = true
	salmonberry_pie = true
	salmonberry_pips = true
	salmonberry_sack = true
	sinigang = true
	smore = true
	venison_chops = true
	wild_salmonberries = true
	#Force the replacement of forge:cheese item tag in recipes with forge:milk
	use_milk_tag = false
	#Allow cooking milk from nuts
	nut_milk = true
	#Allow cooking honey from honey and clovers
	clover_honey = true
	#Give items that are sliced off of blocks directly to player's inventory instead of dropping
	give_sliced_directly = false
	#Allow sliced melons to be juiced in-world (right click)
	melon_juicing = true

[Generation]
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Salmonberries to false above.
	#Range: > 0
	chance_wild_salmonberries = 35
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Mini Melon to false above.
	#Range: > 0
	chance_mini_melon = 35
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Cantaloupe to false above.
	#Range: > 0
	chance_cantaloupe = 55

