
[endrem]
	#Determines if it's possible to obtain the evil eye when trading with a Cleric
	is_evil_eye_obtainable = true
	#Toggle Ender Eyes Actions (Throwing to Locate The Stronghold)
	throw_ender_eye = false
	#Toggle Ender Eyes Actions (Placing in Portal Frames)
	use_ender_eye = false
	#Determines the percentage chance of eyes breaking when thrown
	eye_break_chance = 10
	#Determines whether or not vanilla eyes can naturally generate within the frames of the portal
	frame_has_eye = false
	#Determines if it's possible to obtain the cryptic eye when enchanting
	is_cryptic_eye_obtainable = true
	#Determines whether or not players can remove ender eyes from the portal frames
	can_remove_eye = false

